project:
  type: website
  output-dir: docs
  resources:
    - "*.mp4"
    - "*.wav"

website:
  title: "englert.ai"
  site-url: https://www.englert.ai
  navbar:
    pinned: True
    right:
      - text: Posts
        href: index.qmd
      - text: Archive
        href: archive.qmd
      - icon: rss
        href: index.xml
  google-analytics: <Insert your ID here>
  page-footer: "Â© 2025, englert.ai"
format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css



